version: '3'

services:
  microsservice:
    image: farian/microsservice_app:latest
    container_name: microsserviceCnr
    restart: always
    ports:
      - 8080:8080
  prometheus:
    image: prom/prometheus
    container_name: prometheusCnr
    restart: always
    extra_hosts:
      - host.docker.internal:host-gateway
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:  # corrected typo here
      - ./cnr_conf/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    container_name: grafanaCnr
    ports:
      - 3000:3000
