version: '3.8'

services:
  servicea:
    image: asgharim/service-a:latest
    container_name: servicea_Cnr
    environment:
      - "TZ=Europe/Berlin"
      - "SERVICE_B_URL=http://serviceb_Cnr:8081/service-b"
      - "SERVICE_C_URL=http://servicec_Cnr:8082/service-c"
    command: /bin/sh -c 'apk --no-cache add tzdata && ln -sf /usr/share/zoneinfo/Europe/Berlin /etc/localtime && echo "Europe/Berlin" > /etc/timezone && date'
    restart: always
    ports:
      - 8080:8080
    networks:
      - microservices-network

  serviceb:
    image: asgharim/service-b:latest
    container_name: serviceb_Cnr
    environment:
      - "TZ=Europe/Berlin"
    command: /bin/sh -c 'apk --no-cache add tzdata && ln -sf /usr/share/zoneinfo/Europe/Berlin /etc/localtime && echo "Europe/Berlin" > /etc/timezone && date'
    restart: always
    ports:
      - 8081:8081
    networks:
      - microservices-network

  servicec:
    image: asgharim/service-c:latest
    container_name: servicec_Cnr
    environment:
      - "TZ=Europe/Berlin"
    command: /bin/sh -c 'apk --no-cache add tzdata && ln -sf /usr/share/zoneinfo/Europe/Berlin /etc/localtime && echo "Europe/Berlin" > /etc/timezone && date'
    restart: always
    ports:
      - 8082:8082
    networks:
      - microservices-network

  prometheus:
    image: prom/prometheus
    container_name: prometheusCnr
    restart: always
    environment:
      - TZ=Europe/Berlin
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./cnr_conf/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - microservices-network

  grafana:
    image: grafana/grafana
    container_name: grafanaCnr
    environment:
      - "TZ=Europe/Berlin"
    ports:
      - 3000:3000
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
